### ISSUE TITLE
Error loading control

### ISSUE THREAD

**Issue by jorgeaux** [OOlashyn/PCF-AttachmentGalleryControl#30]
In a model driven app I get this error. Details in the Console are:
msdyn_customcontrolextendedsettings With Id = f79218a8-8aef-e911-a812-000d3a484d80 Does Not Exist

This is the calll that fails: 
http://api/data/v9.0/msdyn_customcontrolextendedsettingses(f79218a8-8aef-e911-a812-000d3a484d80)?$select=msdyn_timelineWall_userFilters

The weird thing is this control is working fine in another model-driven app on the same instance

Do you know why is complaining about that missing settings?

**Comment by OOlashyn** [comment]
Hi @jorgeaux,
Interesting, I don't have any calls msdyn_customcontrolextendedsettings or use it in any way in the control. Do you have a message "Error rendering control" or something like that? Or gallery is rendered and it is just empty?

**Comment by jorgeaux** [comment]
Hi @OOlashyn 

I do get Error loading control.

![image](https://user-images.githubusercontent.com/102974558/200783520-12c74742-3e06-477f-98b2-2e03774e06f0.png)


Actually, these are the error details:
(I just realised that the call to msdyn_customcontrolextendedsettings also fails in the app where your gallery control works, so nothing to do with the Error loaing control)

`Error Details: UciError: Required parameter is null or undefined: id
    at s (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:4847:82)
    at p (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:217:1350)
    at f (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:217:1423)
    at g (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:217:1547)
    at g._validateParamsInternal (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:783:3752)
    at g._executeInternal (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:783:1657)
    at g.executeAsync (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:783:1254)
    at Xt.retrieveRecord (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:2282:4809)
    at https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:2929:8185
    at i (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:351:88)
    at Object.retrieveRecord (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:2929:8149)
    at e.retrieveRecord (https://xyz.crm4.dynamics.com/uclient/scripts/app.js?v=1.4.4958-2210.2:55:7377)
    at e.retrieveRecord (https://xyz.crm4.dynamics.com/uclient/scripts/11.js?v=1.4.4958-2210.2:1:136773)
    at AttachmentPreviewControlUtil.retrieveAttachment (https://xyz.crm4.dynamics.com/%7b638035074500000188%7d/webresources/cc_MscrmControls.Activity.AttachmentPreviewControl/AttachmentPreviewControl.js:1986:39)
    at AttachmentPreviewControl.init (https://xyz.crm4.dynamics.com/%7b638035074500000188%7d/webresources/cc_MscrmControls.Activity.AttachmentPreviewControl/AttachmentPreviewControl.js:1787:55)
    at https://xyz.crm4.dynamics.com/uclient/scripts/11.js?v=1.4.4958-2210.2:1:230221

Activity Id: 9ffa852e-31fe-4b45-bd30-aec8c8b0e4e8`

**Comment by jorgeaux** [comment]
Hi @OOlashyn 

Apologies, I was using another control (not yours)

Have a similar name CC_AttachmentPreviewControl

![image](https://user-images.githubusercontent.com/102974558/200785984-6352ec3b-c470-4e16-9609-a2493b0980be.png)
